# 矩阵操作与数据分析

In [84]:
import numpy as np

## 数组创建

In [85]:
data_matrix = np.arange(0, 100).reshape(10, 10)
data_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## 子矩阵提取

In [86]:
data_matrix[3:7, 3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

## 条件筛选与赋值

In [87]:
mask = data_matrix > 75
data_matrix[mask] = 0

data_matrix


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

## 向量化运算

有点尴尬，发现必须用`astype`转一下类型，`*=`之类的也是`inplace`操作，比`np.multiply`糖一点

In [88]:
data_matrix = data_matrix.astype(np.float64)
data_matrix *= 0.8

data_matrix

array([[ 0. ,  0.8,  1.6,  2.4,  3.2,  4. ,  4.8,  5.6,  6.4,  7.2],
       [ 8. ,  8.8,  9.6, 10.4, 11.2, 12. , 12.8, 13.6, 14.4, 15.2],
       [16. , 16.8, 17.6, 18.4, 19.2, 20. , 20.8, 21.6, 22.4, 23.2],
       [24. , 24.8, 25.6, 26.4, 27.2, 28. , 28.8, 29.6, 30.4, 31.2],
       [32. , 32.8, 33.6, 34.4, 35.2, 36. , 36.8, 37.6, 38.4, 39.2],
       [40. , 40.8, 41.6, 42.4, 43.2, 44. , 44.8, 45.6, 46.4, 47.2],
       [48. , 48.8, 49.6, 50.4, 51.2, 52. , 52.8, 53.6, 54.4, 55.2],
       [56. , 56.8, 57.6, 58.4, 59.2, 60. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

## 数据聚合与定位

In [89]:
max_value = data_matrix.max()
index = np.unravel_index(data_matrix.argmax(), data_matrix.shape)

print(max_value, index)

60.0 (np.int64(7), np.int64(5))
