### 作业 4：广播机制与向量化距离计算（选做）

**目标**：考察对 NumPy 核心特性——广播（Broadcasting）机制的理解与应用，以实现高效的向量化计算。

#### 要求

1. **数据生成**：
   - 创建数组 `points_A`，形状为 `(5， 2)`，代表 5 个点的二维坐标。
   - 创建数组 `points_B`，形状为 `(8， 2)`，代表另外 8 个点的二维坐标。
   - 两个数组的数据均使用 `numpy.random.randint` 在 `[0， 100]` 区间内随机生成。

2. **距离矩阵计算**：
   - 计算 `points_A` 中每个点到 `points_B` 中每个点的欧几里得距离，最终生成一个形状为 `(5， 8)` 的距离矩阵 `distance_matrix`。
   - `distance_matrix[i， j]` 应表示 `points_A[i]` 与 `points_B[j]` 之间的距离。
   - **核心要求**：此过程严禁使用任何形式的显式 `for` 或 `while` 循环。必须利用 NumPy 的广播机制完成。
   - **提示**：考虑使用 `numpy.newaxis` 或 `numpy.reshape` 调整数组维度以触发广播。欧几里得距离公式为 $\sqrt{\sum(p_i - q_i)^2}$。

3. **轴向数据聚合**：
   - 对于 `points_A` 中的每一个点，从 `distance_matrix` 中找出其与 `points_B` 中所有点的最小距离。
   - 结果应为一个长度为 5 的一维数组。
   - **提示**：研究 `numpy.min` 函数的 `axis` 参数。

4. **复合条件查询**：
   - 找出 `points_B` 中，与 `points_A` 中**至少一个点**的距离小于 20 的所有点的**索引**。
   - **提示**：综合运用布尔掩码、`numpy.any` 以及 `numpy.where`。

#### 任务 1 数据生成

In [13]:
import numpy as np

points_A = np.random.randint(0,100,size=(5,2))
points_B = np.random.randint(0,100,size=(8,2))

print(points_A)
print(points_B)

[[87 53]
 [91 54]
 [30 33]
 [91 60]
 [59 39]]
[[50 58]
 [88 71]
 [78 35]
 [76 50]
 [91  0]
 [64 89]
 [75 73]
 [98 11]]


#### 任务 2 距离矩阵计算

In [14]:
points_A_new = points_A[:, np.newaxis ,:]
distance_matrix = np.sqrt(np.sum((points_A_new - points_B) ** 2, axis = 2))

print(distance_matrix)

[[37.33630941 18.02775638 20.1246118  11.40175425 53.15072906 42.72001873
  23.32380758 43.41658669]
 [41.19465985 17.2626765  23.02172887 15.5241747  54.         44.20407221
  24.8394847  43.56604182]
 [32.01562119 69.33974329 48.0416486  49.04079934 69.35416354 65.51335742
  60.20797289 71.47027354]
 [41.0487515  11.40175425 28.17800561 18.02775638 60.         39.62322551
  20.61552813 49.49747468]
 [21.02379604 43.18564576 19.41648784 20.24845673 50.44799302 50.24937811
  37.57658846 48.01041554]]


#### 任务 3 轴向数据聚合

In [15]:
min_matrix = np.min(distance_matrix,axis=1)

print(min_matrix)

[11.40175425 15.5241747  32.01562119 11.40175425 19.41648784]


#### 任务 4 复合条件查询

In [16]:
target_index = np.any(distance_matrix < 20, axis = 0)
target_index = np.where(target_index == True)
target_point = points_B[target_index]

print(target_index)
print(target_point)

(array([1, 2, 3]),)
[[88 71]
 [78 35]
 [76 50]]
