## 创建tensor

In [2]:
import torch

In [2]:
# 从list创建
torch.tensor([1,2,3]), torch.tensor([[1,2,3],[4,5,6]])

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [3]:
import numpy as np

In [4]:
# 从numpy创建
torch.tensor(np.array([1,2,3])), torch.tensor(np.array([[1,2,3],[4,5,6]]))

(tensor([1, 2, 3], dtype=torch.int32),
 tensor([[1, 2, 3],
         [4, 5, 6]], dtype=torch.int32))

In [5]:
# 全1填充
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# 全0填充
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# 随机填充
print(torch.rand(2,3))

tensor([[0.5740, 0.6228, 0.9038],
        [0.4893, 0.0069, 0.5658]])


In [8]:
# full填充
print(torch.full((2,3), 7))

tensor([[7, 7, 7],
        [7, 7, 7]])


In [9]:
# 对角填充
print(torch.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [16]:
# 创建但不初始化
print(torch.empty(2,3))

tensor([[1.9482e+33, 9.2205e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [11]:
# 标准正态分布
print(torch.randn(2,3))

tensor([[-1.2501, -0.3135, -1.0307],
        [ 0.5372,  0.0946,  0.7478]])


In [12]:
# 0-1均匀分布
print(torch.rand(2,3))

tensor([[0.3527, 0.0922, 0.5367],
        [0.5997, 0.7802, 0.7606]])


In [13]:
# 1-9的整数均匀分布
print(torch.randint(1,10,(2,3)))

tensor([[1, 2, 8],
        [4, 5, 9]])


In [19]:
# 自增数列，0-9，步长为2
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [21]:
# 等差数列，0-10，4个数
print(torch.linspace(0,10,4))

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [22]:
# 等比数列，2^0-2^3，4个数
print(torch.logspace(0,3,4,2))

tensor([1., 2., 4., 8.])


In [23]:
# 指定类型的创建
torch.FloatTensor(2,3), torch.LongTensor(2,3), torch.DoubleTensor(2,3)

(tensor([[1.9483e+33, 9.2205e-43, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[2828080843056,             0,             0],
         [            0,             0,             0]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]], dtype=torch.float64))

In [24]:
# 获取数据类型
torch.FloatTensor(2,3).dtype

torch.float32

In [25]:
# 转换数据类型
torch.randn(2,3).to(torch.int64).dtype

torch.int64

## 索引tensor

In [27]:
import torch

# 测试数据
a = torch.randn(4,3,28,28) # 4张3通道28*28的图片
a.shape

torch.Size([4, 3, 28, 28])

In [30]:
# 直接索引
# 查看第一张图片‘
print(a[0].shape)
# 查看第一张图片的第二个通道
print(a[0,1].shape)
# 查看第一张图片的第二个通道的第三行
print(a[0,1,2].shape)
# 查看第一张图片的第二个通道的第三行的第四个元素
print(a[0,1,2,3].shape)

torch.Size([3, 28, 28])
torch.Size([28, 28])
torch.Size([28])
torch.Size([])


In [31]:
# 切片索引
# 查看0-1张图片
print(a[:2].shape)
# 查看0-1张图片的第1-2个通道
print(a[:2,1:3].shape)
# 查看0-1张图片的第1-2个通道的第3-4行
print(a[:2,1:3,2:4].shape)
# 有间隔的切片
print(a[:2,1:3,::2,::2].shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 2, 2, 28])
torch.Size([2, 2, 14, 14])


In [32]:
# 用...代替多个:
# 取前两张图片的0-2列
print(a[:2,...,0:2].shape)
# 取第二张图片
print(a[1,...].shape)

torch.Size([2, 3, 28, 2])
torch.Size([3, 28, 28])


## tensor的维度变换

In [33]:
# view
a = torch.rand(4,1,28,28)
print(a.shape)
# 转换为4*28*28维度，展开通道
print(a.view(4,28,28).shape)
# 转换为4*784维度，打平图片
print(a.view(4,784).shape)
# reshape和view一样
print(a.reshape(4,784).shape)

torch.Size([4, 1, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 784])
torch.Size([4, 784])


In [34]:
# unsqueeze

# 2*2的tensor
a = torch.randn(2,2)
print(a.shape)

# 在第0维增加一个维度
print(a.unsqueeze(0).shape)

# 在倒数1维增加一个维度
print(a.unsqueeze(-1).shape)

torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([2, 2, 1])


In [35]:
# squeeze
 
# 1*2*1*3的tensor
a = torch.randn(1,2,1,3)
print(a.shape)

# 去掉第0维
print(a.squeeze(0).shape)

# 去掉倒数第1维
print(a.squeeze(-2).shape)

# 去掉所有维度为1的维度
print(a.squeeze().shape) 

torch.Size([1, 2, 1, 3])
torch.Size([2, 1, 3])
torch.Size([1, 2, 3])
torch.Size([2, 3])


In [4]:
# repeat

# 分别复制2次和3次
print(torch.randn(2,2).repeat(2,3).shape)

torch.Size([4, 6])


In [5]:
# 维度交换

# t转秩，只能操作2维tensor
print(torch.randn(2,3).t().shape)

# transpose，可以操作多维tensor,只能交换两个维度
print(torch.randn(2,3,4).transpose(1,2).shape)

# permute，可以操作多维tensor，可以交换多个维度
print(torch.randn(2,3,4).permute(2,0,1).shape)

torch.Size([3, 2])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


## Broadcast

In [6]:
import torch
# 自动broadcast
a = torch.randn(2,3)
b = torch.randn(1,3)
c = torch.randn(1)

print((a+b).shape)
print((a+c).shape)

# 手动broadcast
print((b.expand_as(a)).shape)
print((c.expand_as(a)).shape)

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 3])


## tensor的拼接和拆分

In [7]:
import torch

a = torch.rand(2,3)
b = torch.rand(2,3)

# cat拼接,dim=0表示在第0维拼接
print(torch.cat([a,b],dim=0).shape)

torch.Size([4, 3])


In [8]:
a = torch.rand(2,3)
b = torch.rand(2,3)

# stack拼接,会增加一个维度，用于区分a和b
print(torch.stack([a,b],dim=0).shape)

torch.Size([2, 2, 3])


In [9]:
a = torch.rand(2,3)

# split拆分，在维度0上拆分成2份
_1,_2 = torch.split(a,1,dim=0)
print(_1.shape,_2.shape)

# split拆分，按照长度拆分
_1,_2 = torch.split(a,[1,1],dim=0)
print(_1.shape,_2.shape)

torch.Size([1, 3]) torch.Size([1, 3])
torch.Size([1, 3]) torch.Size([1, 3])


In [10]:
a = torch.rand(2,3,4)

# chunk拆分，按照数量拆分
_1,_2 = torch.chunk(a,2,dim=0)
print(_1.shape,_2.shape)

torch.Size([1, 3, 4]) torch.Size([1, 3, 4])


## 数学运算

In [13]:
import torch

# 测试数据
a = torch.FloatTensor([[1,2,3],[4,5,6]])
b = torch.FloatTensor([1,2,3])

a,b

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([1., 2., 3.]))

In [14]:
# 四则运算
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[2., 4., 6.],
        [5., 7., 9.]])
tensor([[0., 0., 0.],
        [3., 3., 3.]])
tensor([[ 1.,  4.,  9.],
        [ 4., 10., 18.]])
tensor([[1.0000, 1.0000, 1.0000],
        [4.0000, 2.5000, 2.0000]])


In [15]:
# 矩阵乘法
print(a@b)
print(a.matmul(b))

tensor([14., 32.])
tensor([14., 32.])


In [16]:
# 指数对数运算
# 指数
print(a**2)

# 开方
print(a.sqrt())

# 求e的指数
print(a.exp())

# 求对数，以e为底
print(a.log())

# 求对数，以2为底
print(a.log2())

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
tensor([[0.0000, 1.0000, 1.5850],
        [2.0000, 2.3219, 2.5850]])


In [17]:
# 逻辑运算
# 大小比较
print(a>b)
print(a<b)
print(a==b)
print(a!=b)

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [ True,  True,  True]])


In [18]:
# 裁剪,限制上下限
a.clamp(0,2)

tensor([[1., 2., 2.],
        [2., 2., 2.]])

In [19]:
# 四舍五入
a = torch.FloatTensor([1.4,2.5,3.6])
# 向下取整
print(a.floor())
# 向上取整
print(a.ceil())
# 四舍五入
print(a.round())

tensor([1., 2., 3.])
tensor([2., 3., 4.])
tensor([1., 2., 4.])


## 属性统计

In [2]:
import torch

# 测试数据
a = torch.FloatTensor([[1,2,3],[4,5,6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
# 求最小
print(a.min())
# 求最大
print(a.max())
# 求最小值的索引
print(a.argmin())
# 求最大值的索引
print(a.argmax())
# 求平均值
print(a.mean())
# 求积
print(a.prod())
# 求和
print(a.sum())

tensor(1.)
tensor(6.)
tensor(0)
tensor(5)
tensor(3.5000)
tensor(720.)
tensor(21.)


In [22]:
# 分维度求最大
print(a.max(dim=0))

torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))


In [23]:
# 分维度求最大值的索引
print(a.argmax(dim=0))

tensor([1, 1, 1])


In [3]:
# 求1范数
print(a.norm(1))
print(a.norm(1,dim=0))

# 求2范数
print(a.norm(2))
print(a.norm(2,dim=0))

tensor(21.)
tensor([5., 7., 9.])
tensor(9.5394)
tensor([4.1231, 5.3852, 6.7082])


In [5]:
# 求前2个最大值
print(a.topk(2,dim=1,largest=True))

torch.return_types.topk(
values=tensor([[3., 2.],
        [6., 5.]]),
indices=tensor([[2, 1],
        [2, 1]]))


In [6]:
# 求第2个最小值
print(a.kthvalue(2,dim=1))

torch.return_types.kthvalue(
values=tensor([2., 5.]),
indices=tensor([1, 1]))
