# 广播机制与向量化距离计算

In [7]:
import numpy as np

## 数据生成

In [8]:
rng = np.random.default_rng()
points_A = rng.integers(0, 100, size=(5, 2), endpoint=True)
points_B = rng.integers(0, 100, size=(8, 2), endpoint=True)

## 距离矩阵计算

In [9]:
# def euclidean_distance(q, p) -> int:

# A -> (5, 1, 2)
# B -> (1, 8, 2)
# O =  (5, 8, 2)

distance_matrix: np.ndarray = np.sqrt(np.sum((points_A[:, np.newaxis, :] - points_B[np.newaxis, :, :]) ** 2, axis=2))

#

distance_matrix

array([[43.0464865 , 27.29468813, 56.08029957, 31.30495168, 44.77722635,
        49.1934955 , 33.37663854, 33.06055051],
       [14.03566885, 19.41648784, 23.85372088, 10.29563014, 47.75981575,
        80.7093551 , 29.73213749, 23.2594067 ],
       [36.22154055, 22.8035085 , 57.218878  , 30.87069808, 82.32860985,
        69.7782201 , 65.76473219, 61.07372594],
       [26.57066051, 20.24845673, 47.07440918, 24.75883681, 79.92496481,
        79.40403012, 62.42595614, 56.85068161],
       [81.04319836, 78.89233169, 77.00649323, 75.23961722, 19.6468827 ,
        90.02777349, 37.64306045, 44.38468204]])

## 轴向数据聚合

In [10]:
min_distance = distance_matrix.min(axis=1)

min_distance

array([27.29468813, 10.29563014, 22.8035085 , 20.24845673, 19.6468827 ])

## 复合条件查询

In [11]:
indexes_mark = np.any(distance_matrix<20, axis=0)
indexes = np.arange(8)[indexes_mark]

indexes

array([0, 1, 3, 4])