### 作业三：矩阵操作与数据分析（选做）

#### 要求

1. **数组创建**：创建一个形状为 `(10， 10)` 的 NumPy 数组，命名为 `data_matrix`，使其包含从 0 到 99 的连续整数。
   - 应使用 `numpy.arange` 和 `numpy.reshape` 方法完成。

2. **子矩阵提取**：从 `data_matrix` 中提取出位于中心的 `4x4` 子矩阵。

3. **条件筛选与赋值**：
   - 在 `data_matrix` 中定位所有数值大于 75 的元素。
   - 使用布尔索引（Boolean Indexing）将这些元素的值全部重置为 0。此操作禁止使用任何形式的显式循环。

4. **向量化运算**：对上一步处理后的 `data_matrix` 进行整体缩放，将矩阵中的所有元素乘以 `0.8`。此操作应直接在原数组上（in-place）完成。

5. **数据聚合与定位**：
   - 找出最终矩阵中的最大值。
   - 确定该最大值在矩阵中的行和列索引。
   - **提示**：可结合使用 `numpy.argmax` 和 `numpy.unravel_index` 来高效完成定位。

#### 任务 1 数组创建

In [1]:
import numpy as np

data_matrix = np.arange(0,100,1)
data_matrix = data_matrix.reshape((10,10))

print(data_matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### 任务 2 子矩阵提取

In [2]:
print(data_matrix[3:7,3:7])

[[33 34 35 36]
 [43 44 45 46]
 [53 54 55 56]
 [63 64 65 66]]


#### 任务 3 条件筛选与赋值

In [3]:
data_matrix = np.where(data_matrix > 75, 0, data_matrix)
print(data_matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### 任务 4 向量化运算

In [4]:
data_matrix  = data_matrix * 0.8
print(data_matrix)

[[ 0.   0.8  1.6  2.4  3.2  4.   4.8  5.6  6.4  7.2]
 [ 8.   8.8  9.6 10.4 11.2 12.  12.8 13.6 14.4 15.2]
 [16.  16.8 17.6 18.4 19.2 20.  20.8 21.6 22.4 23.2]
 [24.  24.8 25.6 26.4 27.2 28.  28.8 29.6 30.4 31.2]
 [32.  32.8 33.6 34.4 35.2 36.  36.8 37.6 38.4 39.2]
 [40.  40.8 41.6 42.4 43.2 44.  44.8 45.6 46.4 47.2]
 [48.  48.8 49.6 50.4 51.2 52.  52.8 53.6 54.4 55.2]
 [56.  56.8 57.6 58.4 59.2 60.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]


#### 任务 5 数据聚合与定位

In [5]:
max_data_index = np.argmax(data_matrix)
max_data_index = np.unravel_index(max_data_index, (10,10), order = 'C')
print(max_data_index, data_matrix[max_data_index])

max_data = np.max(data_matrix)
max_data_index = np.where(data_matrix == max_data)
print(max_data_index, max_data)

(np.int64(7), np.int64(5)) 60.0
(array([7]), array([5])) 60.0
